# -*- coding: utf-8 -*-
"""new.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wczug22RnwHYzVHpDB8F3QxWSlscNXh
"""

def vikas():
  print("ECE & CYBER")
  a= int(input("enter number"))
  print(b= a*a)